apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multitool-daemon
  namespace: default
  labels:
    k8s-app: multitool-daemon
spec:
  selector:
    matchLabels:
      name: multitool-daemon
  template:
    metadata:
      labels:
        name: multitool-daemon
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        env:
          - name: HTTP_PORT
            value: "1180"
          - name: HTTPS_PORT
            value: "11443"
        ports:
          - containerPort: 1180
            name: http-port
          - containerPort: 11443
            name: https-port
        resources:
          requests:
            cpu: "1m"
            memory: "20Mi"
        volumeMounts:
          - name: volume2
            mountPath: /mnt/log
      volumes:
      - name: volume2
      :
          path: /var/log/